import pygame

mattis = pygame.image.load("images/gameset/mattis.png")
mathias = pygame.image.load("images/gameset/mathias.png")

thomas = pygame.image.load("images/gameset/thomas.png")

Iaccueil = pygame.image.load("images/gameset/accueil.png")

ideath = pygame.image.load("images/gameset/ideath.png")

ilose = pygame.image.load("images/gameset/ilose.png")

iwin = pygame.image.load("images/gameset/iwin.png")

imenu = pygame.image.load("images/gameset/mainmenu.png")
imenu2 = pygame.image.load("images/gameset/mainmenu3.png")
iloading = pygame.image.load("images/gameset/loading.png")

coin = pygame.image.load("images/gameset/coin.png")
check = pygame.image.load("images/gameset/check.png")

#lobby + level4
cloud = pygame.image.load("images/level1/bg_cloud_C.png")
brick = pygame.image.load("images/level1/brick.png")
Ddirt = pygame.image.load("images/level1/Ddirt.png")
Ldirt = pygame.image.load("images/level1/Ldirt.png")
DLdirt = pygame.image.load("images/level1/DLdirt.png")
DRdirt = pygame.image.load("images/level1/DRdirt.png")
Rdirt = pygame.image.load("images/level1/Rdirt.png")
Mdirt = pygame.image.load("images/level1/Mdirt.png")
Lgrass = pygame.image.load("images/level1/Lgrass.png")
Mgrass = pygame.image.load("images/level1/Mgrass.png")
Rgrass = pygame.image.load("images/level1/Rgrass.png")
water = pygame.image.load("images/level1/water.png")
grotte = pygame.image.load("images/level1/grotte.png")
jewel_green = pygame.image.load("images/level1/jewel green.png")
little_rock = pygame.image.load("images/level1/little rock.png")
rock = pygame.image.load("images/level1/rock.png")
bliane = pygame.image.load("images/level1/bliane.png")
mliane = pygame.image.load("images/level1/mliane.png")
tliane = pygame.image.load("images/level1/tliane.png")
flower = pygame.image.load("images/level1/flower.png")
bottom_tree = pygame.image.load("images/level1/bottom tree.png")
middle_tree = pygame.image.load("images/level1/middle tree.png")
top_tree = pygame.image.load("images/level1/top tree.png")
rock_plat = pygame.image.load("images/level1/rockplat.png")
top_echelle = pygame.image.load("images/level1/top echelle.png")
echelle = pygame.image.load("images/level1/echelle.png")
bottom_echelle = pygame.image.load("images/level1/bottom echelle.png")
box_type_1 = pygame.image.load("images/level1/box type 1.png")
box_type_2 = pygame.image.load("images/level1/box type 2.png")
buisson_fleurs = pygame.image.load("images/level1/buisson fleurs.png")
trampoline = pygame.image.load("images/level1/trampoline.png")
open_door = pygame.image.load("images/level1/open_door.png")
mariostar = pygame.image.load("images/level1/mariostar.png")
flechedroite = pygame.image.load("images/level1/flechedroite.png")
flechegauche = pygame.image.load("images/level1/flechegauche.png")
flechehaut = pygame.image.load("images/level1/flechehaut.png")
flechebas = pygame.image.load("images/level1/flechebas.png")
objet0 = pygame.image.load("images/level1/objet0.png")
objet1 = pygame.image.load("images/level1/objet1.png")
objet2 = pygame.image.load("images/level1/objet2.png")
objet3 = pygame.image.load("images/level1/objet3.png")
vie1 = pygame.image.load("images/level1/1life.png")
vie2 = pygame.image.load("images/level1/2life.png")
vie3 = pygame.image.load("images/level1/3life.png")

################################################################
#level 2
cloud1 = pygame.image.load("images/level2/cloud1.png")
cloud2 = pygame.image.load("images/level2/cloud2.png")
cloud3 = pygame.image.load("images/level2/cloud3.png")
cloud4 = pygame.image.load("images/level2/cloud4.png")
midground_center = pygame.image.load("images/level2/midground_center.png")
midground_left_A = pygame.image.load("images/level2/midground_left_A.png")
midground_left_A_shadowed = pygame.image.load("images/level2/midground_left_A_shadowed.png")
midground_left_B = pygame.image.load("images/level2/midground_left_B.png")
midground_left_C = pygame.image.load("images/level2/midground_left_C.png")
midground_left_C_shadowed = pygame.image.load("images/level2/midground_left_C_shadowed.png")
midground_right_A = pygame.image.load("images/level2/midground_right_A.png")
midground_right_A_shadowed = pygame.image.load("images/level2/midground_right_A_shadowed.png")
midground_right_B = pygame.image.load("images/level2/midground_right_B.png")
midground_right_C = pygame.image.load("images/level2/midground_right_C.png")
midground_right_C_shadowed = pygame.image.load("images/level2/midground_right_C_shadowed.png")
terrain_center = pygame.image.load("images/level2/terrain_center.png")
terrain_center2 = pygame.image.load("images/level2/terrain_center2.png")
terrain_center_left = pygame.image.load("images/level2/terrain_center_left.png")
terrain_center_right = pygame.image.load("images/level2/terrain_center_right.png")
terrain_corner_inner_bottom_left = pygame.image.load("images/level2/terrain_corner_inner_bottom_left.png")
terrain_corner_inner_bottom_right = pygame.image.load("images/level2/terrain_corner_inner_bottom_right.png")
terrain_slope_ceiling_A = pygame.image.load("images/level2/terrain_slope_ceiling_A.png")
terrain_slope_ceiling_B = pygame.image.load("images/level2/terrain_slope_ceiling_B.png")
terrain_slope_floor_A = pygame.image.load("images/level2/terrain_slope_floor_A.png")
terrain_slope_floor_B = pygame.image.load("images/level2/terrain_slope_floor_B.png")
terrain_top_center = pygame.image.load("images/level2/terrain_top_center.png")
doormathias = pygame.image.load("images/level2/doormathias.png")
jewel_yellow = pygame.image.load("images/level2/jewel yellow.png")
jewel_blue = pygame.image.load("images/level2/jewel blue.png")
################################################################
#level 3
#lvl3_background = pygame.image.load("images/level3/Middleground.png")
lvl3_big_block = pygame.image.load("images/level3/lvl3bigblock.png")
lvl3_block = pygame.image.load("images/level3/lvl3block.png")
lvl3_crate = pygame.image.load("images/level3/lvl3crate.png")
lvl3_face_block = pygame.image.load("images/level3/lvl3faceblock.png")
lvl3_grass = pygame.image.load("images/level3/lvl3grass.png")
lvl3_herb2 = pygame.image.load("images/level3/lvl3herb2.png")
lvl3_house = pygame.image.load("images/level3/lvl3house.png")
lvl3_platform = pygame.image.load("images/level3/lvl3platform.png")
lvl3_rock1_L = pygame.image.load("images/level3/lvl3rock1L.png")
lvl3_rock1_R = pygame.image.load("images/level3/lvl3rock1R.png")
lvl3_rock2 = pygame.image.load("images/level3/lvl3rock2.png")
lvl3_rock3 = pygame.image.load("images/level3/lvl3rock3.png")
lvl3_rock4 = pygame.image.load("images/level3/lvl3rock4.png")
lvl3_rock5 = pygame.image.load("images/level3/lvl3rock5.png")
lvl3_rock6 = pygame.image.load("images/level3/lvl3rock6.png")
lvl3_sign = pygame.image.load("images/level3/lvl3sign.png")
lvl3_spikes = pygame.image.load("images/level3/lvl3spikes.png")
lvl3_tree = pygame.image.load("images/level3/lvl3tree.png")

